/**
 * AUTO-GENERATED by make_catalog.py — do not edit by hand.
 * Import these in data.ts instead of hardcoding counts.
 */
export const PLOTTER = {
  run:        16,
  factories:  17,
  pieces:     "12,741",
  kept:       "12,629",
  curated:    "1,296",
  best:       "89.1",
  withheld:   "11,333",
} as const;
