/**
 * AUTO-GENERATED by make_catalog.py — do not edit by hand.
 * Import these in data.ts instead of hardcoding counts.
 */
export const PLOTTER = {
  run:        16,
  factories:  23,
  pieces:     "21,770",
  kept:       "20,845",
  curated:    "1,296",
  best:       "89.1",
  withheld:   "19,549",
} as const;
